export const MESSAGE_MAIN = 'MESSAGE_MAIN';
export const MESSAGE_MINI = 'MESSAGE_MINI';

export const OPEN_DIALOG_CONFIRM = 'OPEN_DIALOG_CONFIRM';
export const CLOSE_DIALOG_CONFIRM = 'CLOSE_DIALOG_CONFIRM';
export const LOADING_CONFIRM = 'LOADING_CONFIRM';

export const OPEN_DIALOG_UPLOAD_IMG = 'OPEN_DIALOG_UPLOAD_IMG';
export const PROCESS_DIALOG_UPLOAD_IMG = 'PROCESS_DIALOG_UPLOAD_IMG';
export const CLOSE_DIALOG_UPLOAD_IMG = 'CLOSE_DIALOG_UPLOAD_IMG';

export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_ERROR = 'LOGIN_ADMIN_ERROR';

export const LOGOUT_ADMIN = 'LOGOUT_ADMIN';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_ERROR = 'FORGET_PASSWORD_ERROR';

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_ERROR = 'UPLOAD_AVATAR_ERROR';

export const UPLOAD_AVATAR_DIRECTLY = 'UPLOAD_AVATAR_DIRECTLY';
export const UPLOAD_AVATAR_DIRECTLY_SUCCESS = 'UPLOAD_AVATAR_DIRECTLY_SUCCESS';
export const UPLOAD_AVATAR_DIRECTLY_ERROR = 'UPLOAD_AVATAR_DIRECTLY_ERROR';

export const DISTRICTS_BELONGTO_PROVINCE = 'DISTRICTS_BELONGTO_PROVINCE';
export const DISTRICTS_BELONGTO_PROVINCE_SUCCESS = 'DISTRICTS_BELONGTO_PROVINCE_SUCCESS';
export const DISTRICTS_BELONGTO_PROVINCE_ERROR = 'DISTRICTS_BELONGTO_PROVINCE_ERROR';

export const COMMUNES_BELONGTO_DISTRICT = 'COMMUNES_BELONGTO_DISTRICT';
export const COMMUNES_BELONGTO_DISTRICT_SUCCESS = 'COMMUNES_BELONGTO_DISTRICT_SUCCESS';
export const COMMUNES_BELONGTO_DISTRICT_ERROR = 'COMMUNES_BELONGTO_DISTRICT_ERROR';

export const GET_PROVINCES = 'GET_PROVINCES';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';
export const GET_PROVINCES_ERROR = 'GET_PROVINCES_ERROR';

export const GET_DISTRICTS = 'GET_DISTRICTS';
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICTS_SUCCESS';
export const GET_DISTRICTS_ERROR = 'GET_DISTRICTS_ERROR';

export const GET_COMMUNES = 'GET_COMMUNES';
export const GET_COMMUNES_SUCCESS = 'GET_COMMUNES_SUCCESS';
export const GET_COMMUNES_ERROR = 'GET_COMMUNES_ERROR';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const OPEN_FORM_ADD_USER = 'OPEN_FORM_ADD_USER';
export const CLOSE_FORM_ADD_USER = 'CLOSE_FORM_ADD_USER';

export const GET_ALL_USER_ERROR = 'GET_ALL_USER_ERROR';
export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';

export const LOCK_USERS_ERROR = 'LOCK_USERS_ERROR';
export const LOCK_USERS = 'LOCK_USERS';
export const LOCK_USERS_SUCCESS = 'LOCK_USERS_SUCCESS';

export const GET_USER_DETAIL_ERROR = 'GET_USER_DETAIL_ERROR';
export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';

export const DISTROY_USER = 'DISTROY_USER';
export const UNLOCK_USERS = 'UNLOCK_USERS';

export const SEND_ACTION_ERROR = 'SEND_ACTION_ERROR';
export const SEND_ACTION = 'SEND_ACTION';
export const SEND_ACTION_SUCCESS = 'SEND_ACTION_SUCCESS';

export const GET_USER_EDIT_ERROR = 'GET_USER_EDIT_ERROR';
export const GET_USER_EDIT = 'GET_USER_EDIT';
export const GET_USER_EDIT_SUCCESS = 'GET_USER_EDIT_SUCCESS';
export const UPLOAD_AVATAR_COMPLATE = 'UPLOAD_AVATAR_COMPLATE';

export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';

export const UPDATE_MY_PROFILE = 'UPDATE_MY_PROFILE';
export const UPDATE_MY_PROFILE_SUCCESS = 'UPDATE_MY_PROFILE_SUCCESS';
export const UPDATE_MY_PROFILE_ERROR = 'UPDATE_MY_PROFILE_ERROR';

export const GET_NOTIFY_RULES = 'GET_NOTIFY_RULES';
export const GET_NOTIFY_RULES_SUCCESS = 'GET_NOTIFY_RULES_SUCCESS';

export const UPDATE_NOTIFY_RULES = 'UPDATE_NOTIFY_RULES';
export const UPDATE_NOTIFY_RULES_SUCCESS = 'UPDATE_NOTIFY_RULES_SUCCESS';
export const UPDATE_NOTIFY_RULES_ERROR = 'UPDATE_NOTIFY_RULES_ERROR';

