export const MESSAGE_MAIN = 'MESSAGE_MAIN';
export const MESSAGE_MINI = 'MESSAGE_MINI';

export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_ERROR = 'LOGIN_ADMIN_ERROR';

export const LOGOUT_ADMIN = 'LOGOUT_ADMIN';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_ERROR = 'FORGET_PASSWORD_ERROR';

export const ADMIN_PROFILE = 'ADMIN_PROFILE';
export const ADMIN_PROFILE_SUCCESS = 'ADMIN_PROFILE_SUCCESS';
export const ADMIN_PROFILE_ERROR = 'ADMIN_PROFILE_ERROR';

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_ERROR = 'UPLOAD_AVATAR_ERROR';

export const ADMIN_DETAIL = 'ADMIN_DETAIL';
export const ADMIN_DETAIL_SUCCESS = 'ADMIN_DETAIL_SUCCESS';
export const ADMIN_DETAIL_ERROR = 'ADMIN_DETAIL__ERROR';

export const DISTRICTS_BELONGTO_PROVINCE = 'DISTRICTS_BELONGTO_PROVINCE';
export const DISTRICTS_BELONGTO_PROVINCE_SUCCESS = 'DISTRICTS_BELONGTO_PROVINCE_SUCCESS';
export const DISTRICTS_BELONGTO_PROVINCE_ERROR = 'DISTRICTS_BELONGTO_PROVINCE__ERROR';

export const COMMUNES_BELONGTO_DISTRICT = 'COMMUNES_BELONGTO_DISTRICT';
export const COMMUNES_BELONGTO_DISTRICT_SUCCESS = 'COMMUNES_BELONGTO_DISTRICT_SUCCESS';
export const COMMUNES_BELONGTO_DISTRICT_ERROR = 'COMMUNES_BELONGTO_DISTRICT__ERROR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE__ERROR';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER__ERROR';
export const OPEN_FORM_ADD_USER = 'OPEN_FORM_ADD_USER';
export const CLOSE_FORM_ADD_USER = 'CLOSE_FORM_ADD_USER';

