export const MESSAGE_MAIN = 'MESSAGE_MAIN';
export const MESSAGE_MINI = 'MESSAGE_MINI';

export const OPEN_DIALOG_CONFIRM = 'OPEN_DIALOG_CONFIRM';
export const CLOSE_DIALOG_CONFIRM = 'CLOSE_DIALOG_CONFIRM';
export const LOADING_CONFIRM = 'LOADING_CONFIRM';

export const OPEN_DIALOG_UPLOAD_IMG = 'OPEN_DIALOG_UPLOAD_IMG';
export const PROCESS_DIALOG_UPLOAD_IMG = 'PROCESS_DIALOG_UPLOAD_IMG';
export const CLOSE_DIALOG_UPLOAD_IMG = 'CLOSE_DIALOG_UPLOAD_IMG';

export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_ERROR = 'LOGIN_ADMIN_ERROR';

export const LOGOUT_ADMIN = 'LOGOUT_ADMIN';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_ERROR = 'FORGET_PASSWORD_ERROR';

export const ADMIN_PROFILE = 'ADMIN_PROFILE';
export const ADMIN_PROFILE_SUCCESS = 'ADMIN_PROFILE_SUCCESS';
export const ADMIN_PROFILE_ERROR = 'ADMIN_PROFILE_ERROR';

export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_ERROR = 'UPLOAD_AVATAR_ERROR';

export const ADMIN_DETAIL = 'ADMIN_DETAIL';
export const ADMIN_DETAIL_SUCCESS = 'ADMIN_DETAIL_SUCCESS';
export const ADMIN_DETAIL_ERROR = 'ADMIN_DETAIL_ERROR';

export const DISTRICTS_BELONGTO_PROVINCE = 'DISTRICTS_BELONGTO_PROVINCE';
export const DISTRICTS_BELONGTO_PROVINCE_SUCCESS = 'DISTRICTS_BELONGTO_PROVINCE_SUCCESS';
export const DISTRICTS_BELONGTO_PROVINCE_ERROR = 'DISTRICTS_BELONGTO_PROVINCE_ERROR';

export const COMMUNES_BELONGTO_DISTRICT = 'COMMUNES_BELONGTO_DISTRICT';
export const COMMUNES_BELONGTO_DISTRICT_SUCCESS = 'COMMUNES_BELONGTO_DISTRICT_SUCCESS';
export const COMMUNES_BELONGTO_DISTRICT_ERROR = 'COMMUNES_BELONGTO_DISTRICT_ERROR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const OPEN_FORM_ADD_USER = 'OPEN_FORM_ADD_USER';
export const CLOSE_FORM_ADD_USER = 'CLOSE_FORM_ADD_USER';

export const GET_ALL_USER_ERROR = 'GET_ALL_USER_ERROR';
export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';

export const LOCK_USERS_ERROR = 'LOCK_USERS_ERROR';
export const LOCK_USERS = 'LOCK_USERS';
export const LOCK_USERS_SUCCESS = 'LOCK_USERS_SUCCESS';

export const GET_USER_DETAIL_ERROR = 'GET_USER_DETAIL_ERROR';
export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';

export const DISTROY_USER = 'DISTROY_USER';
export const UNLOCK_USERS = 'UNLOCK_USERS';

export const SEND_ACTION_ERROR = 'SEND_ACTION_ERROR';
export const SEND_ACTION = 'SEND_ACTION';
export const SEND_ACTION_SUCCESS = 'SEND_ACTION_SUCCESS';

export const GET_USER_EDIT_ERROR = 'GET_USER_EDIT_ERROR';
export const GET_USER_EDIT = 'GET_USER_EDIT';
export const GET_USER_EDIT_SUCCESS = 'GET_USER_EDIT_SUCCESS';

